/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPurchasesIndexRouteImport } from './routes/_authenticated/purchases.index'
import { Route as AuthenticatedIngredientsIndexRouteImport } from './routes/_authenticated/ingredients.index'
import { Route as AuthenticatedPurchasesNewRouteImport } from './routes/_authenticated/purchases.new'
import { Route as AuthenticatedIngredientsNewRouteImport } from './routes/_authenticated/ingredients.new'
import { Route as AuthenticatedIngredientsIdRouteImport } from './routes/_authenticated/ingredients.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPurchasesIndexRoute =
  AuthenticatedPurchasesIndexRouteImport.update({
    id: '/purchases/',
    path: '/purchases/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIngredientsIndexRoute =
  AuthenticatedIngredientsIndexRouteImport.update({
    id: '/ingredients/',
    path: '/ingredients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPurchasesNewRoute =
  AuthenticatedPurchasesNewRouteImport.update({
    id: '/purchases/new',
    path: '/purchases/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIngredientsNewRoute =
  AuthenticatedIngredientsNewRouteImport.update({
    id: '/ingredients/new',
    path: '/ingredients/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIngredientsIdRoute =
  AuthenticatedIngredientsIdRouteImport.update({
    id: '/ingredients/$id',
    path: '/ingredients/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ingredients/$id': typeof AuthenticatedIngredientsIdRoute
  '/ingredients/new': typeof AuthenticatedIngredientsNewRoute
  '/purchases/new': typeof AuthenticatedPurchasesNewRoute
  '/ingredients/': typeof AuthenticatedIngredientsIndexRoute
  '/purchases/': typeof AuthenticatedPurchasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ingredients/$id': typeof AuthenticatedIngredientsIdRoute
  '/ingredients/new': typeof AuthenticatedIngredientsNewRoute
  '/purchases/new': typeof AuthenticatedPurchasesNewRoute
  '/ingredients': typeof AuthenticatedIngredientsIndexRoute
  '/purchases': typeof AuthenticatedPurchasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/ingredients/$id': typeof AuthenticatedIngredientsIdRoute
  '/_authenticated/ingredients/new': typeof AuthenticatedIngredientsNewRoute
  '/_authenticated/purchases/new': typeof AuthenticatedPurchasesNewRoute
  '/_authenticated/ingredients/': typeof AuthenticatedIngredientsIndexRoute
  '/_authenticated/purchases/': typeof AuthenticatedPurchasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/ingredients/$id'
    | '/ingredients/new'
    | '/purchases/new'
    | '/ingredients/'
    | '/purchases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/ingredients/$id'
    | '/ingredients/new'
    | '/purchases/new'
    | '/ingredients'
    | '/purchases'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/ingredients/$id'
    | '/_authenticated/ingredients/new'
    | '/_authenticated/purchases/new'
    | '/_authenticated/ingredients/'
    | '/_authenticated/purchases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchases/': {
      id: '/_authenticated/purchases/'
      path: '/purchases'
      fullPath: '/purchases/'
      preLoaderRoute: typeof AuthenticatedPurchasesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ingredients/': {
      id: '/_authenticated/ingredients/'
      path: '/ingredients'
      fullPath: '/ingredients/'
      preLoaderRoute: typeof AuthenticatedIngredientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchases/new': {
      id: '/_authenticated/purchases/new'
      path: '/purchases/new'
      fullPath: '/purchases/new'
      preLoaderRoute: typeof AuthenticatedPurchasesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ingredients/new': {
      id: '/_authenticated/ingredients/new'
      path: '/ingredients/new'
      fullPath: '/ingredients/new'
      preLoaderRoute: typeof AuthenticatedIngredientsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ingredients/$id': {
      id: '/_authenticated/ingredients/$id'
      path: '/ingredients/$id'
      fullPath: '/ingredients/$id'
      preLoaderRoute: typeof AuthenticatedIngredientsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIngredientsIdRoute: typeof AuthenticatedIngredientsIdRoute
  AuthenticatedIngredientsNewRoute: typeof AuthenticatedIngredientsNewRoute
  AuthenticatedPurchasesNewRoute: typeof AuthenticatedPurchasesNewRoute
  AuthenticatedIngredientsIndexRoute: typeof AuthenticatedIngredientsIndexRoute
  AuthenticatedPurchasesIndexRoute: typeof AuthenticatedPurchasesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIngredientsIdRoute: AuthenticatedIngredientsIdRoute,
  AuthenticatedIngredientsNewRoute: AuthenticatedIngredientsNewRoute,
  AuthenticatedPurchasesNewRoute: AuthenticatedPurchasesNewRoute,
  AuthenticatedIngredientsIndexRoute: AuthenticatedIngredientsIndexRoute,
  AuthenticatedPurchasesIndexRoute: AuthenticatedPurchasesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
