/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CountTokenRouteImport } from './routes/count.$token'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedRecipesIndexRouteImport } from './routes/_authenticated/recipes.index'
import { Route as AuthenticatedPurchasesIndexRouteImport } from './routes/_authenticated/purchases.index'
import { Route as AuthenticatedMovementsIndexRouteImport } from './routes/_authenticated/movements.index'
import { Route as AuthenticatedInventoriesIndexRouteImport } from './routes/_authenticated/inventories.index'
import { Route as AuthenticatedIngredientsIndexRouteImport } from './routes/_authenticated/ingredients.index'
import { Route as AuthenticatedGroupsIndexRouteImport } from './routes/_authenticated/groups.index'
import { Route as AuthenticatedRecipesNewRouteImport } from './routes/_authenticated/recipes.new'
import { Route as AuthenticatedPurchasesNewRouteImport } from './routes/_authenticated/purchases.new'
import { Route as AuthenticatedInventoriesNewRouteImport } from './routes/_authenticated/inventories.new'
import { Route as AuthenticatedInventoriesIdRouteImport } from './routes/_authenticated/inventories.$id'
import { Route as AuthenticatedIngredientsNewRouteImport } from './routes/_authenticated/ingredients.new'
import { Route as AuthenticatedIngredientsIdRouteImport } from './routes/_authenticated/ingredients.$id'
import { Route as AuthenticatedGroupsIdRouteImport } from './routes/_authenticated/groups.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountTokenRoute = CountTokenRouteImport.update({
  id: '/count/$token',
  path: '/count/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecipesIndexRoute =
  AuthenticatedRecipesIndexRouteImport.update({
    id: '/recipes/',
    path: '/recipes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPurchasesIndexRoute =
  AuthenticatedPurchasesIndexRouteImport.update({
    id: '/purchases/',
    path: '/purchases/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMovementsIndexRoute =
  AuthenticatedMovementsIndexRouteImport.update({
    id: '/movements/',
    path: '/movements/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoriesIndexRoute =
  AuthenticatedInventoriesIndexRouteImport.update({
    id: '/inventories/',
    path: '/inventories/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIngredientsIndexRoute =
  AuthenticatedIngredientsIndexRouteImport.update({
    id: '/ingredients/',
    path: '/ingredients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGroupsIndexRoute =
  AuthenticatedGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecipesNewRoute = AuthenticatedRecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPurchasesNewRoute =
  AuthenticatedPurchasesNewRouteImport.update({
    id: '/purchases/new',
    path: '/purchases/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoriesNewRoute =
  AuthenticatedInventoriesNewRouteImport.update({
    id: '/inventories/new',
    path: '/inventories/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoriesIdRoute =
  AuthenticatedInventoriesIdRouteImport.update({
    id: '/inventories/$id',
    path: '/inventories/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIngredientsNewRoute =
  AuthenticatedIngredientsNewRouteImport.update({
    id: '/ingredients/new',
    path: '/ingredients/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIngredientsIdRoute =
  AuthenticatedIngredientsIdRouteImport.update({
    id: '/ingredients/$id',
    path: '/ingredients/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGroupsIdRoute = AuthenticatedGroupsIdRouteImport.update({
  id: '/groups/$id',
  path: '/groups/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/count/$token': typeof CountTokenRoute
  '/groups/$id': typeof AuthenticatedGroupsIdRoute
  '/ingredients/$id': typeof AuthenticatedIngredientsIdRoute
  '/ingredients/new': typeof AuthenticatedIngredientsNewRoute
  '/inventories/$id': typeof AuthenticatedInventoriesIdRoute
  '/inventories/new': typeof AuthenticatedInventoriesNewRoute
  '/purchases/new': typeof AuthenticatedPurchasesNewRoute
  '/recipes/new': typeof AuthenticatedRecipesNewRoute
  '/groups/': typeof AuthenticatedGroupsIndexRoute
  '/ingredients/': typeof AuthenticatedIngredientsIndexRoute
  '/inventories/': typeof AuthenticatedInventoriesIndexRoute
  '/movements/': typeof AuthenticatedMovementsIndexRoute
  '/purchases/': typeof AuthenticatedPurchasesIndexRoute
  '/recipes/': typeof AuthenticatedRecipesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/count/$token': typeof CountTokenRoute
  '/groups/$id': typeof AuthenticatedGroupsIdRoute
  '/ingredients/$id': typeof AuthenticatedIngredientsIdRoute
  '/ingredients/new': typeof AuthenticatedIngredientsNewRoute
  '/inventories/$id': typeof AuthenticatedInventoriesIdRoute
  '/inventories/new': typeof AuthenticatedInventoriesNewRoute
  '/purchases/new': typeof AuthenticatedPurchasesNewRoute
  '/recipes/new': typeof AuthenticatedRecipesNewRoute
  '/groups': typeof AuthenticatedGroupsIndexRoute
  '/ingredients': typeof AuthenticatedIngredientsIndexRoute
  '/inventories': typeof AuthenticatedInventoriesIndexRoute
  '/movements': typeof AuthenticatedMovementsIndexRoute
  '/purchases': typeof AuthenticatedPurchasesIndexRoute
  '/recipes': typeof AuthenticatedRecipesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/count/$token': typeof CountTokenRoute
  '/_authenticated/groups/$id': typeof AuthenticatedGroupsIdRoute
  '/_authenticated/ingredients/$id': typeof AuthenticatedIngredientsIdRoute
  '/_authenticated/ingredients/new': typeof AuthenticatedIngredientsNewRoute
  '/_authenticated/inventories/$id': typeof AuthenticatedInventoriesIdRoute
  '/_authenticated/inventories/new': typeof AuthenticatedInventoriesNewRoute
  '/_authenticated/purchases/new': typeof AuthenticatedPurchasesNewRoute
  '/_authenticated/recipes/new': typeof AuthenticatedRecipesNewRoute
  '/_authenticated/groups/': typeof AuthenticatedGroupsIndexRoute
  '/_authenticated/ingredients/': typeof AuthenticatedIngredientsIndexRoute
  '/_authenticated/inventories/': typeof AuthenticatedInventoriesIndexRoute
  '/_authenticated/movements/': typeof AuthenticatedMovementsIndexRoute
  '/_authenticated/purchases/': typeof AuthenticatedPurchasesIndexRoute
  '/_authenticated/recipes/': typeof AuthenticatedRecipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/count/$token'
    | '/groups/$id'
    | '/ingredients/$id'
    | '/ingredients/new'
    | '/inventories/$id'
    | '/inventories/new'
    | '/purchases/new'
    | '/recipes/new'
    | '/groups/'
    | '/ingredients/'
    | '/inventories/'
    | '/movements/'
    | '/purchases/'
    | '/recipes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/count/$token'
    | '/groups/$id'
    | '/ingredients/$id'
    | '/ingredients/new'
    | '/inventories/$id'
    | '/inventories/new'
    | '/purchases/new'
    | '/recipes/new'
    | '/groups'
    | '/ingredients'
    | '/inventories'
    | '/movements'
    | '/purchases'
    | '/recipes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/count/$token'
    | '/_authenticated/groups/$id'
    | '/_authenticated/ingredients/$id'
    | '/_authenticated/ingredients/new'
    | '/_authenticated/inventories/$id'
    | '/_authenticated/inventories/new'
    | '/_authenticated/purchases/new'
    | '/_authenticated/recipes/new'
    | '/_authenticated/groups/'
    | '/_authenticated/ingredients/'
    | '/_authenticated/inventories/'
    | '/_authenticated/movements/'
    | '/_authenticated/purchases/'
    | '/_authenticated/recipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  CountTokenRoute: typeof CountTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/count/$token': {
      id: '/count/$token'
      path: '/count/$token'
      fullPath: '/count/$token'
      preLoaderRoute: typeof CountTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/': {
      id: '/_authenticated/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof AuthenticatedRecipesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchases/': {
      id: '/_authenticated/purchases/'
      path: '/purchases'
      fullPath: '/purchases/'
      preLoaderRoute: typeof AuthenticatedPurchasesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/movements/': {
      id: '/_authenticated/movements/'
      path: '/movements'
      fullPath: '/movements/'
      preLoaderRoute: typeof AuthenticatedMovementsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventories/': {
      id: '/_authenticated/inventories/'
      path: '/inventories'
      fullPath: '/inventories/'
      preLoaderRoute: typeof AuthenticatedInventoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ingredients/': {
      id: '/_authenticated/ingredients/'
      path: '/ingredients'
      fullPath: '/ingredients/'
      preLoaderRoute: typeof AuthenticatedIngredientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/groups/': {
      id: '/_authenticated/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthenticatedGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/new': {
      id: '/_authenticated/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof AuthenticatedRecipesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchases/new': {
      id: '/_authenticated/purchases/new'
      path: '/purchases/new'
      fullPath: '/purchases/new'
      preLoaderRoute: typeof AuthenticatedPurchasesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventories/new': {
      id: '/_authenticated/inventories/new'
      path: '/inventories/new'
      fullPath: '/inventories/new'
      preLoaderRoute: typeof AuthenticatedInventoriesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventories/$id': {
      id: '/_authenticated/inventories/$id'
      path: '/inventories/$id'
      fullPath: '/inventories/$id'
      preLoaderRoute: typeof AuthenticatedInventoriesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ingredients/new': {
      id: '/_authenticated/ingredients/new'
      path: '/ingredients/new'
      fullPath: '/ingredients/new'
      preLoaderRoute: typeof AuthenticatedIngredientsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ingredients/$id': {
      id: '/_authenticated/ingredients/$id'
      path: '/ingredients/$id'
      fullPath: '/ingredients/$id'
      preLoaderRoute: typeof AuthenticatedIngredientsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/groups/$id': {
      id: '/_authenticated/groups/$id'
      path: '/groups/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof AuthenticatedGroupsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGroupsIdRoute: typeof AuthenticatedGroupsIdRoute
  AuthenticatedIngredientsIdRoute: typeof AuthenticatedIngredientsIdRoute
  AuthenticatedIngredientsNewRoute: typeof AuthenticatedIngredientsNewRoute
  AuthenticatedInventoriesIdRoute: typeof AuthenticatedInventoriesIdRoute
  AuthenticatedInventoriesNewRoute: typeof AuthenticatedInventoriesNewRoute
  AuthenticatedPurchasesNewRoute: typeof AuthenticatedPurchasesNewRoute
  AuthenticatedRecipesNewRoute: typeof AuthenticatedRecipesNewRoute
  AuthenticatedGroupsIndexRoute: typeof AuthenticatedGroupsIndexRoute
  AuthenticatedIngredientsIndexRoute: typeof AuthenticatedIngredientsIndexRoute
  AuthenticatedInventoriesIndexRoute: typeof AuthenticatedInventoriesIndexRoute
  AuthenticatedMovementsIndexRoute: typeof AuthenticatedMovementsIndexRoute
  AuthenticatedPurchasesIndexRoute: typeof AuthenticatedPurchasesIndexRoute
  AuthenticatedRecipesIndexRoute: typeof AuthenticatedRecipesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGroupsIdRoute: AuthenticatedGroupsIdRoute,
  AuthenticatedIngredientsIdRoute: AuthenticatedIngredientsIdRoute,
  AuthenticatedIngredientsNewRoute: AuthenticatedIngredientsNewRoute,
  AuthenticatedInventoriesIdRoute: AuthenticatedInventoriesIdRoute,
  AuthenticatedInventoriesNewRoute: AuthenticatedInventoriesNewRoute,
  AuthenticatedPurchasesNewRoute: AuthenticatedPurchasesNewRoute,
  AuthenticatedRecipesNewRoute: AuthenticatedRecipesNewRoute,
  AuthenticatedGroupsIndexRoute: AuthenticatedGroupsIndexRoute,
  AuthenticatedIngredientsIndexRoute: AuthenticatedIngredientsIndexRoute,
  AuthenticatedInventoriesIndexRoute: AuthenticatedInventoriesIndexRoute,
  AuthenticatedMovementsIndexRoute: AuthenticatedMovementsIndexRoute,
  AuthenticatedPurchasesIndexRoute: AuthenticatedPurchasesIndexRoute,
  AuthenticatedRecipesIndexRoute: AuthenticatedRecipesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  CountTokenRoute: CountTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
