/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CountTokenRouteImport } from './routes/count.$token'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedRecipesIndexRouteImport } from './routes/_authenticated/recipes.index'
import { Route as AuthenticatedPurchasesIndexRouteImport } from './routes/_authenticated/purchases.index'
import { Route as AuthenticatedProductionsIndexRouteImport } from './routes/_authenticated/productions.index'
import { Route as AuthenticatedPricingIndexRouteImport } from './routes/_authenticated/pricing.index'
import { Route as AuthenticatedMovementsIndexRouteImport } from './routes/_authenticated/movements.index'
import { Route as AuthenticatedMenuAnalysisIndexRouteImport } from './routes/_authenticated/menu-analysis.index'
import { Route as AuthenticatedInventoriesIndexRouteImport } from './routes/_authenticated/inventories.index'
import { Route as AuthenticatedIngredientsIndexRouteImport } from './routes/_authenticated/ingredients.index'
import { Route as AuthenticatedGroupsIndexRouteImport } from './routes/_authenticated/groups.index'
import { Route as AuthenticatedCmvIndexRouteImport } from './routes/_authenticated/cmv.index'
import { Route as AuthenticatedRecipesNewRouteImport } from './routes/_authenticated/recipes.new'
import { Route as AuthenticatedRecipesIdRouteImport } from './routes/_authenticated/recipes.$id'
import { Route as AuthenticatedPurchasesNewRouteImport } from './routes/_authenticated/purchases.new'
import { Route as AuthenticatedMenuAnalysisIdRouteImport } from './routes/_authenticated/menu-analysis.$id'
import { Route as AuthenticatedInventoriesNewRouteImport } from './routes/_authenticated/inventories.new'
import { Route as AuthenticatedInventoriesIdRouteImport } from './routes/_authenticated/inventories.$id'
import { Route as AuthenticatedIngredientsNewRouteImport } from './routes/_authenticated/ingredients.new'
import { Route as AuthenticatedIngredientsIdRouteImport } from './routes/_authenticated/ingredients.$id'
import { Route as AuthenticatedGroupsIdRouteImport } from './routes/_authenticated/groups.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountTokenRoute = CountTokenRouteImport.update({
  id: '/count/$token',
  path: '/count/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRecipesIndexRoute =
  AuthenticatedRecipesIndexRouteImport.update({
    id: '/recipes/',
    path: '/recipes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPurchasesIndexRoute =
  AuthenticatedPurchasesIndexRouteImport.update({
    id: '/purchases/',
    path: '/purchases/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductionsIndexRoute =
  AuthenticatedProductionsIndexRouteImport.update({
    id: '/productions/',
    path: '/productions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPricingIndexRoute =
  AuthenticatedPricingIndexRouteImport.update({
    id: '/pricing/',
    path: '/pricing/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMovementsIndexRoute =
  AuthenticatedMovementsIndexRouteImport.update({
    id: '/movements/',
    path: '/movements/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMenuAnalysisIndexRoute =
  AuthenticatedMenuAnalysisIndexRouteImport.update({
    id: '/menu-analysis/',
    path: '/menu-analysis/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoriesIndexRoute =
  AuthenticatedInventoriesIndexRouteImport.update({
    id: '/inventories/',
    path: '/inventories/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIngredientsIndexRoute =
  AuthenticatedIngredientsIndexRouteImport.update({
    id: '/ingredients/',
    path: '/ingredients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGroupsIndexRoute =
  AuthenticatedGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCmvIndexRoute = AuthenticatedCmvIndexRouteImport.update({
  id: '/cmv/',
  path: '/cmv/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecipesNewRoute = AuthenticatedRecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecipesIdRoute = AuthenticatedRecipesIdRouteImport.update({
  id: '/recipes/$id',
  path: '/recipes/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPurchasesNewRoute =
  AuthenticatedPurchasesNewRouteImport.update({
    id: '/purchases/new',
    path: '/purchases/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMenuAnalysisIdRoute =
  AuthenticatedMenuAnalysisIdRouteImport.update({
    id: '/menu-analysis/$id',
    path: '/menu-analysis/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoriesNewRoute =
  AuthenticatedInventoriesNewRouteImport.update({
    id: '/inventories/new',
    path: '/inventories/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoriesIdRoute =
  AuthenticatedInventoriesIdRouteImport.update({
    id: '/inventories/$id',
    path: '/inventories/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIngredientsNewRoute =
  AuthenticatedIngredientsNewRouteImport.update({
    id: '/ingredients/new',
    path: '/ingredients/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIngredientsIdRoute =
  AuthenticatedIngredientsIdRouteImport.update({
    id: '/ingredients/$id',
    path: '/ingredients/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGroupsIdRoute = AuthenticatedGroupsIdRouteImport.update({
  id: '/groups/$id',
  path: '/groups/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/signup': typeof SignupRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/count/$token': typeof CountTokenRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/groups/$id': typeof AuthenticatedGroupsIdRoute
  '/ingredients/$id': typeof AuthenticatedIngredientsIdRoute
  '/ingredients/new': typeof AuthenticatedIngredientsNewRoute
  '/inventories/$id': typeof AuthenticatedInventoriesIdRoute
  '/inventories/new': typeof AuthenticatedInventoriesNewRoute
  '/menu-analysis/$id': typeof AuthenticatedMenuAnalysisIdRoute
  '/purchases/new': typeof AuthenticatedPurchasesNewRoute
  '/recipes/$id': typeof AuthenticatedRecipesIdRoute
  '/recipes/new': typeof AuthenticatedRecipesNewRoute
  '/cmv/': typeof AuthenticatedCmvIndexRoute
  '/groups/': typeof AuthenticatedGroupsIndexRoute
  '/ingredients/': typeof AuthenticatedIngredientsIndexRoute
  '/inventories/': typeof AuthenticatedInventoriesIndexRoute
  '/menu-analysis/': typeof AuthenticatedMenuAnalysisIndexRoute
  '/movements/': typeof AuthenticatedMovementsIndexRoute
  '/pricing/': typeof AuthenticatedPricingIndexRoute
  '/productions/': typeof AuthenticatedProductionsIndexRoute
  '/purchases/': typeof AuthenticatedPurchasesIndexRoute
  '/recipes/': typeof AuthenticatedRecipesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/signup': typeof SignupRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/count/$token': typeof CountTokenRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/groups/$id': typeof AuthenticatedGroupsIdRoute
  '/ingredients/$id': typeof AuthenticatedIngredientsIdRoute
  '/ingredients/new': typeof AuthenticatedIngredientsNewRoute
  '/inventories/$id': typeof AuthenticatedInventoriesIdRoute
  '/inventories/new': typeof AuthenticatedInventoriesNewRoute
  '/menu-analysis/$id': typeof AuthenticatedMenuAnalysisIdRoute
  '/purchases/new': typeof AuthenticatedPurchasesNewRoute
  '/recipes/$id': typeof AuthenticatedRecipesIdRoute
  '/recipes/new': typeof AuthenticatedRecipesNewRoute
  '/cmv': typeof AuthenticatedCmvIndexRoute
  '/groups': typeof AuthenticatedGroupsIndexRoute
  '/ingredients': typeof AuthenticatedIngredientsIndexRoute
  '/inventories': typeof AuthenticatedInventoriesIndexRoute
  '/menu-analysis': typeof AuthenticatedMenuAnalysisIndexRoute
  '/movements': typeof AuthenticatedMovementsIndexRoute
  '/pricing': typeof AuthenticatedPricingIndexRoute
  '/productions': typeof AuthenticatedProductionsIndexRoute
  '/purchases': typeof AuthenticatedPurchasesIndexRoute
  '/recipes': typeof AuthenticatedRecipesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/signup': typeof SignupRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/count/$token': typeof CountTokenRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/groups/$id': typeof AuthenticatedGroupsIdRoute
  '/_authenticated/ingredients/$id': typeof AuthenticatedIngredientsIdRoute
  '/_authenticated/ingredients/new': typeof AuthenticatedIngredientsNewRoute
  '/_authenticated/inventories/$id': typeof AuthenticatedInventoriesIdRoute
  '/_authenticated/inventories/new': typeof AuthenticatedInventoriesNewRoute
  '/_authenticated/menu-analysis/$id': typeof AuthenticatedMenuAnalysisIdRoute
  '/_authenticated/purchases/new': typeof AuthenticatedPurchasesNewRoute
  '/_authenticated/recipes/$id': typeof AuthenticatedRecipesIdRoute
  '/_authenticated/recipes/new': typeof AuthenticatedRecipesNewRoute
  '/_authenticated/cmv/': typeof AuthenticatedCmvIndexRoute
  '/_authenticated/groups/': typeof AuthenticatedGroupsIndexRoute
  '/_authenticated/ingredients/': typeof AuthenticatedIngredientsIndexRoute
  '/_authenticated/inventories/': typeof AuthenticatedInventoriesIndexRoute
  '/_authenticated/menu-analysis/': typeof AuthenticatedMenuAnalysisIndexRoute
  '/_authenticated/movements/': typeof AuthenticatedMovementsIndexRoute
  '/_authenticated/pricing/': typeof AuthenticatedPricingIndexRoute
  '/_authenticated/productions/': typeof AuthenticatedProductionsIndexRoute
  '/_authenticated/purchases/': typeof AuthenticatedPurchasesIndexRoute
  '/_authenticated/recipes/': typeof AuthenticatedRecipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mcp'
    | '/signup'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/count/$token'
    | '/.mcp/invoke-tool/$tool'
    | '/groups/$id'
    | '/ingredients/$id'
    | '/ingredients/new'
    | '/inventories/$id'
    | '/inventories/new'
    | '/menu-analysis/$id'
    | '/purchases/new'
    | '/recipes/$id'
    | '/recipes/new'
    | '/cmv/'
    | '/groups/'
    | '/ingredients/'
    | '/inventories/'
    | '/menu-analysis/'
    | '/movements/'
    | '/pricing/'
    | '/productions/'
    | '/purchases/'
    | '/recipes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mcp'
    | '/signup'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/count/$token'
    | '/.mcp/invoke-tool/$tool'
    | '/groups/$id'
    | '/ingredients/$id'
    | '/ingredients/new'
    | '/inventories/$id'
    | '/inventories/new'
    | '/menu-analysis/$id'
    | '/purchases/new'
    | '/recipes/$id'
    | '/recipes/new'
    | '/cmv'
    | '/groups'
    | '/ingredients'
    | '/inventories'
    | '/menu-analysis'
    | '/movements'
    | '/pricing'
    | '/productions'
    | '/purchases'
    | '/recipes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/mcp'
    | '/signup'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/dashboard'
    | '/count/$token'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/groups/$id'
    | '/_authenticated/ingredients/$id'
    | '/_authenticated/ingredients/new'
    | '/_authenticated/inventories/$id'
    | '/_authenticated/inventories/new'
    | '/_authenticated/menu-analysis/$id'
    | '/_authenticated/purchases/new'
    | '/_authenticated/recipes/$id'
    | '/_authenticated/recipes/new'
    | '/_authenticated/cmv/'
    | '/_authenticated/groups/'
    | '/_authenticated/ingredients/'
    | '/_authenticated/inventories/'
    | '/_authenticated/menu-analysis/'
    | '/_authenticated/movements/'
    | '/_authenticated/pricing/'
    | '/_authenticated/productions/'
    | '/_authenticated/purchases/'
    | '/_authenticated/recipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  SignupRoute: typeof SignupRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CountTokenRoute: typeof CountTokenRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/count/$token': {
      id: '/count/$token'
      path: '/count/$token'
      fullPath: '/count/$token'
      preLoaderRoute: typeof CountTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recipes/': {
      id: '/_authenticated/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof AuthenticatedRecipesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchases/': {
      id: '/_authenticated/purchases/'
      path: '/purchases'
      fullPath: '/purchases/'
      preLoaderRoute: typeof AuthenticatedPurchasesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/productions/': {
      id: '/_authenticated/productions/'
      path: '/productions'
      fullPath: '/productions/'
      preLoaderRoute: typeof AuthenticatedProductionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pricing/': {
      id: '/_authenticated/pricing/'
      path: '/pricing'
      fullPath: '/pricing/'
      preLoaderRoute: typeof AuthenticatedPricingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/movements/': {
      id: '/_authenticated/movements/'
      path: '/movements'
      fullPath: '/movements/'
      preLoaderRoute: typeof AuthenticatedMovementsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/menu-analysis/': {
      id: '/_authenticated/menu-analysis/'
      path: '/menu-analysis'
      fullPath: '/menu-analysis/'
      preLoaderRoute: typeof AuthenticatedMenuAnalysisIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventories/': {
      id: '/_authenticated/inventories/'
      path: '/inventories'
      fullPath: '/inventories/'
      preLoaderRoute: typeof AuthenticatedInventoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ingredients/': {
      id: '/_authenticated/ingredients/'
      path: '/ingredients'
      fullPath: '/ingredients/'
      preLoaderRoute: typeof AuthenticatedIngredientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/groups/': {
      id: '/_authenticated/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthenticatedGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cmv/': {
      id: '/_authenticated/cmv/'
      path: '/cmv'
      fullPath: '/cmv/'
      preLoaderRoute: typeof AuthenticatedCmvIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/new': {
      id: '/_authenticated/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof AuthenticatedRecipesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/$id': {
      id: '/_authenticated/recipes/$id'
      path: '/recipes/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof AuthenticatedRecipesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchases/new': {
      id: '/_authenticated/purchases/new'
      path: '/purchases/new'
      fullPath: '/purchases/new'
      preLoaderRoute: typeof AuthenticatedPurchasesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/menu-analysis/$id': {
      id: '/_authenticated/menu-analysis/$id'
      path: '/menu-analysis/$id'
      fullPath: '/menu-analysis/$id'
      preLoaderRoute: typeof AuthenticatedMenuAnalysisIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventories/new': {
      id: '/_authenticated/inventories/new'
      path: '/inventories/new'
      fullPath: '/inventories/new'
      preLoaderRoute: typeof AuthenticatedInventoriesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventories/$id': {
      id: '/_authenticated/inventories/$id'
      path: '/inventories/$id'
      fullPath: '/inventories/$id'
      preLoaderRoute: typeof AuthenticatedInventoriesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ingredients/new': {
      id: '/_authenticated/ingredients/new'
      path: '/ingredients/new'
      fullPath: '/ingredients/new'
      preLoaderRoute: typeof AuthenticatedIngredientsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ingredients/$id': {
      id: '/_authenticated/ingredients/$id'
      path: '/ingredients/$id'
      fullPath: '/ingredients/$id'
      preLoaderRoute: typeof AuthenticatedIngredientsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/groups/$id': {
      id: '/_authenticated/groups/$id'
      path: '/groups/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof AuthenticatedGroupsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGroupsIdRoute: typeof AuthenticatedGroupsIdRoute
  AuthenticatedIngredientsIdRoute: typeof AuthenticatedIngredientsIdRoute
  AuthenticatedIngredientsNewRoute: typeof AuthenticatedIngredientsNewRoute
  AuthenticatedInventoriesIdRoute: typeof AuthenticatedInventoriesIdRoute
  AuthenticatedInventoriesNewRoute: typeof AuthenticatedInventoriesNewRoute
  AuthenticatedMenuAnalysisIdRoute: typeof AuthenticatedMenuAnalysisIdRoute
  AuthenticatedPurchasesNewRoute: typeof AuthenticatedPurchasesNewRoute
  AuthenticatedRecipesIdRoute: typeof AuthenticatedRecipesIdRoute
  AuthenticatedRecipesNewRoute: typeof AuthenticatedRecipesNewRoute
  AuthenticatedCmvIndexRoute: typeof AuthenticatedCmvIndexRoute
  AuthenticatedGroupsIndexRoute: typeof AuthenticatedGroupsIndexRoute
  AuthenticatedIngredientsIndexRoute: typeof AuthenticatedIngredientsIndexRoute
  AuthenticatedInventoriesIndexRoute: typeof AuthenticatedInventoriesIndexRoute
  AuthenticatedMenuAnalysisIndexRoute: typeof AuthenticatedMenuAnalysisIndexRoute
  AuthenticatedMovementsIndexRoute: typeof AuthenticatedMovementsIndexRoute
  AuthenticatedPricingIndexRoute: typeof AuthenticatedPricingIndexRoute
  AuthenticatedProductionsIndexRoute: typeof AuthenticatedProductionsIndexRoute
  AuthenticatedPurchasesIndexRoute: typeof AuthenticatedPurchasesIndexRoute
  AuthenticatedRecipesIndexRoute: typeof AuthenticatedRecipesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGroupsIdRoute: AuthenticatedGroupsIdRoute,
  AuthenticatedIngredientsIdRoute: AuthenticatedIngredientsIdRoute,
  AuthenticatedIngredientsNewRoute: AuthenticatedIngredientsNewRoute,
  AuthenticatedInventoriesIdRoute: AuthenticatedInventoriesIdRoute,
  AuthenticatedInventoriesNewRoute: AuthenticatedInventoriesNewRoute,
  AuthenticatedMenuAnalysisIdRoute: AuthenticatedMenuAnalysisIdRoute,
  AuthenticatedPurchasesNewRoute: AuthenticatedPurchasesNewRoute,
  AuthenticatedRecipesIdRoute: AuthenticatedRecipesIdRoute,
  AuthenticatedRecipesNewRoute: AuthenticatedRecipesNewRoute,
  AuthenticatedCmvIndexRoute: AuthenticatedCmvIndexRoute,
  AuthenticatedGroupsIndexRoute: AuthenticatedGroupsIndexRoute,
  AuthenticatedIngredientsIndexRoute: AuthenticatedIngredientsIndexRoute,
  AuthenticatedInventoriesIndexRoute: AuthenticatedInventoriesIndexRoute,
  AuthenticatedMenuAnalysisIndexRoute: AuthenticatedMenuAnalysisIndexRoute,
  AuthenticatedMovementsIndexRoute: AuthenticatedMovementsIndexRoute,
  AuthenticatedPricingIndexRoute: AuthenticatedPricingIndexRoute,
  AuthenticatedProductionsIndexRoute: AuthenticatedProductionsIndexRoute,
  AuthenticatedPurchasesIndexRoute: AuthenticatedPurchasesIndexRoute,
  AuthenticatedRecipesIndexRoute: AuthenticatedRecipesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  SignupRoute: SignupRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CountTokenRoute: CountTokenRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
